# This is a basic workflow to help you get started with Actions

name: Sync Branches

# Controls when the action will run. 
on:
  # Triggers the workflow on push events
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: nelonoel/branch-name@v1.0.1

      # Runs a single command using the runners shell
      - name: Run sync command
        run: curl https://servel.ngrok.io/sync/${BRANCH_NAME}
